import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Products.js";

dotenv.config();

const products = [
  {
    name: "Wireless Headphones",
    price: 4999,
    category: "Electronics",
    stock: 20,
    description:
      "High quality wireless headphones with noise cancellation and 30hr battery life.",
    image: "http://localhost:5000/images/headphones.jpg",
  },
  {
    name: "Smart Watch",
    price: 8999,
    category: "Electronics",
    stock: 15,
    description:
      "Feature-rich smartwatch with health tracking, GPS and AMOLED display.",
    image: "http://localhost:5000/images/smartwatch.jpg",
  },
  {
    name: "Laptop",
    price: 85000,
    category: "Electronics",
    stock: 10,
    description:
      "High performance laptop with Intel i7, 16GB RAM and 512GB SSD.",
    image: "http://localhost:5000/images/laptop.jpg",
  },
  {
    name: "Coffee Maker",
    price: 5499,
    category: "Home & Kitchen",
    stock: 8,
    description: "Programmable drip coffee maker with thermal carafe.",
    image: "http://localhost:5000/images/coffeemaker.jpg",
  },
  {
    name: "Soft Chair",
    price: 12000,
    category: "Furniture",
    stock: 5,
    description:
      "Ergonomic soft chair with lumbar support, perfect for home office.",
    image: "http://localhost:5000/images/chair.jpg",
  },
  {
    name: "Running Shoes",
    price: 3499,
    category: "Footwear",
    stock: 30,
    description:
      "Lightweight running shoes with cushioned sole for everyday training.",
    image: "http://localhost:5000/images/shoes.jpg",
  },
  {
    name: "Cotton T-Shirt",
    price: 899,
    category: "Clothing",
    stock: 50,
    description:
      "Comfortable 100% cotton t-shirt available in multiple colors.",
    image: "http://localhost:5000/images/tshirt.jpg",
  },
  {
    name: "Backpack",
    price: 2199,
    category: "Accessories",
    stock: 25,
    description:
      "Durable travel backpack with laptop compartment and USB charging port.",
    image: "http://localhost:5000/images/backpack.jpg",
  },
  {
    name: "Yoga Mat",
    price: 1299,
    category: "Sports",
    stock: 20,
    description: "Non-slip yoga mat with alignment lines, 6mm thickness.",
    image: "http://localhost:5000/images/yogamat.jpg",
  },
  {
    name: "Blender",
    price: 3999,
    category: "Home & Kitchen",
    stock: 12,
    description: "High speed blender for smoothies, soups and sauces.",
    image: "http://localhost:5000/images/blender.jpg",
  },
  {
    name: "Smartwatch",
    price: 7999,
    category: "Electronics",
    stock: 10,
    description: "Feature-rich smartwatch with health tracking.",
    image: "https://placehold.co/400x400?text=Smartwatch",
  },
  {
    name: "Laptop",
    price: 85000,
    category: "Electronics",
    stock: 8,
    description: "High performance laptop with Intel i7.",
    image: "https://placehold.co/400x400?text=Laptop",
  },
  {
    name: "GoPro Camera",
    price: 45000,
    category: "Electronics",
    stock: 5,
    description: "Action camera with 4K recording.",
    image: "https://placehold.co/400x400?text=GoPro",
  },
  {
    name: "Headphones",
    price: 4999,
    category: "Electronics",
    stock: 20,
    description: "Wireless headphones with noise cancellation.",
    image: "https://placehold.co/400x400?text=Headphones",
  },
  {
    name: "Canon Camera",
    price: 55000,
    category: "Electronics",
    stock: 6,
    description: "DSLR camera with 100x zoom.",
    image: "https://placehold.co/400x400?text=Canon",
  },
  {
    name: "Soft Chair",
    price: 12000,
    category: "Furniture",
    stock: 5,
    description: "Ergonomic soft chair with lumbar support.",
    image: "https://placehold.co/400x400?text=Chair",
  },
  {
    name: "Sofa",
    price: 35000,
    category: "Furniture",
    stock: 3,
    description: "3-seater sofa with premium fabric.",
    image: "https://placehold.co/400x400?text=Sofa",
  },
  {
    name: "Kitchen Dishes",
    price: 1999,
    category: "Home & Kitchen",
    stock: 30,
    description: "Premium ceramic dinner set.",
    image: "https://placehold.co/400x400?text=Dishes",
  },
  {
    name: "Kitchen Mixer",
    price: 8999,
    category: "Home & Kitchen",
    stock: 12,
    description: "Stand mixer with multiple attachments.",
    image: "https://placehold.co/400x400?text=Mixer",
  },
  {
    name: "Blender",
    price: 3999,
    category: "Home & Kitchen",
    stock: 15,
    description: "High speed blender for smoothies.",
    image: "https://placehold.co/400x400?text=Blender",
  },
  {
    name: "Home Appliance",
    price: 5999,
    category: "Home & Kitchen",
    stock: 10,
    description: "Multi-purpose home appliance.",
    image: "https://placehold.co/400x400?text=Appliance",
  },
  {
    name: "Coffee Maker",
    price: 5499,
    category: "Home & Kitchen",
    stock: 8,
    description: "Drip coffee maker with programmable timer.",
    image: "https://placehold.co/400x400?text=Coffee+Maker",
  },
  {
    name: "Camera",
    price: 32000,
    category: "Electronics",
    stock: 7,
    description: "Digital camera with optical zoom.",
    image: "https://placehold.co/400x400?text=Camera",
  },
  {
    name: "Gaming Set",
    price: 15000,
    category: "Electronics",
    stock: 10,
    description: "Complete gaming setup with headset and controller.",
    image: "https://placehold.co/400x400?text=Gaming",
  },
  {
    name: "Smartphone",
    price: 45000,
    category: "Electronics",
    stock: 20,
    description: "Latest smartphone with powerful processor.",
    image: "https://placehold.co/400x400?text=Phone",
  },
  {
    name: "Electric Kettle",
    price: 2499,
    category: "Home & Kitchen",
    stock: 25,
    description: "Fast boiling electric kettle.",
    image: "https://placehold.co/400x400?text=Kettle",
  },
  {
    name: "Smart watches",
    price: 7999,
    category: "Electronics",
    stock: 15,
    description:
      "Feature-rich smartwatch with health tracking, GPS and AMOLED display.",
    image: "https://placehold.co/400x400?text=Smartwatch",
  },
  {
    name: "Laptops",
    price: 85000,
    category: "Electronics",
    stock: 8,
    description:
      "High performance laptop with Intel i7, 16GB RAM and 512GB SSD.",
    image: "https://placehold.co/400x400?text=Laptop",
  },
  {
    name: "GoPro cameras",
    price: 45000,
    category: "Electronics",
    stock: 5,
    description: "Action camera with 4K recording.",
    image: "https://placehold.co/400x400?text=GoPro",
  },
  {
    name: "Headphones",
    price: 4999,
    category: "Electronics",
    stock: 20,
    description: "Wireless headphones with noise cancellation.",
    image: "https://placehold.co/400x400?text=Headphones",
  },
  {
    name: "Canon cameras",
    price: 55000,
    category: "Electronics",
    stock: 6,
    description: "DSLR camera with 100x zoom.",
    image: "https://placehold.co/400x400?text=Canon",
  },
  {
    name: "Soft chairs",
    price: 12000,
    category: "Furniture",
    stock: 5,
    description: "Ergonomic soft chair with lumbar support.",
    image: "https://placehold.co/400x400?text=Chair",
  },
  {
    name: "Sofa & chair",
    price: 35000,
    category: "Furniture",
    stock: 3,
    description: "3-seater sofa with premium fabric.",
    image: "https://placehold.co/400x400?text=Sofa",
  },
  {
    name: "Kitchen dishes",
    price: 1999,
    category: "Home & Kitchen",
    stock: 30,
    description: "Premium ceramic dinner set.",
    image: "https://placehold.co/400x400?text=Dishes",
  },
  {
    name: "Kitchen mixer",
    price: 8999,
    category: "Home & Kitchen",
    stock: 12,
    description: "Stand mixer with multiple attachments.",
    image: "https://placehold.co/400x400?text=Mixer",
  },
  {
    name: "Blenders",
    price: 3999,
    category: "Home & Kitchen",
    stock: 15,
    description: "High speed blender for smoothies.",
    image: "https://placehold.co/400x400?text=Blender",
  },
  {
    name: "Home appliance",
    price: 5999,
    category: "Home & Kitchen",
    stock: 10,
    description: "Multi-purpose home appliance.",
    image: "https://placehold.co/400x400?text=Appliance",
  },
  {
    name: "Coffee maker",
    price: 5499,
    category: "Home & Kitchen",
    stock: 8,
    description: "Drip coffee maker with programmable timer.",
    image: "https://placehold.co/400x400?text=Coffee+Maker",
  },
  {
    name: "Cameras",
    price: 32000,
    category: "Electronics",
    stock: 7,
    description: "Digital camera with optical zoom.",
    image: "https://placehold.co/400x400?text=Camera",
  },
  {
    name: "Gaming set",
    price: 15000,
    category: "Electronics",
    stock: 10,
    description: "Complete gaming setup with headset and controller.",
    image: "https://placehold.co/400x400?text=Gaming",
  },
  {
    name: "Laptops & PC",
    price: 75000,
    category: "Electronics",
    stock: 12,
    description: "High performance laptops and desktop computers.",
    image: "https://placehold.co/400x400?text=PC",
  },
  {
    name: "Smartphones",
    price: 45000,
    category: "Electronics",
    stock: 20,
    description: "Latest smartphones with powerful processors.",
    image: "https://placehold.co/400x400?text=Phone",
  },
  {
    name: "Electric kettle",
    price: 2499,
    category: "Home & Kitchen",
    stock: 25,
    description: "Fast boiling electric kettle.",
    image: "https://placehold.co/400x400?text=Kettle",
  },
  {
    name: "Running shoes",
    price: 3499,
    category: "Footwear",
    stock: 30,
    description: "Lightweight running shoes with cushioned sole.",
    image: "https://placehold.co/400x400?text=Shoes",
  },
  {
    name: "Cotton T-Shirt",
    price: 899,
    category: "Clothing",
    stock: 50,
    description: "Comfortable 100% cotton t-shirt.",
    image: "https://placehold.co/400x400?text=T-Shirt",
  },
  {
    name: "Backpack",
    price: 2199,
    category: "Accessories",
    stock: 25,
    description: "Durable travel backpack with laptop compartment.",
    image: "https://placehold.co/400x400?text=Backpack",
  },
  {
    name: "Yoga mat",
    price: 1299,
    category: "Sports",
    stock: 20,
    description: "Non-slip yoga mat with alignment lines.",
    image: "https://placehold.co/400x400?text=Yoga+Mat",
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    await Product.deleteMany(); // clear existing
    await Product.insertMany(products);
    console.log("Database seeded!");
    process.exit();
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
